### ISSUE TITLE
[BUG REPORT] Microsoft Store Version

### ISSUE THREAD

**Issue by ToraxOutlaw** [OhMyGuus/BetterCrewLink#10]
I helped streamer friend of mine download and setup the latest version of BetterCrewLink. But everytime he the clicks open game button, it opens steam up. 

He got the Microsoft Store version, thanks to Xbox Games Pass for PC, is there anyway to fix this issue so he doesn't have to open up BetterCrewLink and then manually open up Among Us separately.

**Comment by Unkn0wnNode** [comment]
Yeah, the open button is used to open up the steam version of the game. This is how it was designed. There is a command to find the directory I believe but this is one of those low-priority Feature Requests

**Comment by Ricoculous** [comment]
Update: used 7-zip to extract the 32-bit version and run it. Guus got on to test with me. Had to change the voice server to the crewlink server and it worked perfectly. 

Thanks Guus!
