### ISSUE TITLE
[FEATURE] Add ability to run CrewLink on PC but play on Android 

### ISSUE THREAD

**Issue by Phoenix616** [OhMyGuus/BetterCrewLink#11]
**Is your feature request related to a problem? Please describe.**

Some people want to play the game on mobile but still want to use their normal voice chat equipment like with Discord.

**Describe the solution you'd like**

The ability to run (Better)CrewLink on the PC while playing on a mobile device. (I guess that would work similarly to the mobile app and require at least one PC player to provide the position data)

**Describe alternatives you've considered**

Running the mobile app and somehow getting your audio equipment to work/sent to it. Really not ideal for the mass.

**Comment by OhMyGuus** [comment]
U can use the web version of bettercrewlink mobile, currently this doesn't work for non https voice server or official crewlink servers tho.
https://web.bettercrewl.ink/

**Comment by Phoenix616** [comment]
Interesting, thanks or the link! Didn't know that was a thing.

**Comment by OhMyGuus** [comment]
Its now fully possible and working with the voice server: 
https://bettercrewl.ink and the website https://web.bettercrewl.ink
