### ISSUE TITLE
[FEATURE] Impostor radio, allowing impostors to talk covertly

### ISSUE THREAD

**Issue by higps** [OhMyGuus/BetterCrewLink#119]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x ] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
2. [x ] I have checked that someone else has not suggested this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)
3. [x ] My feature request is not one of the **commonly suggested features**:
- iOS app (its already being development)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Adding a hotkey to allow impostors to talk to each other regardless of distance when button is pressed, crewmates will not be able to hear what impostors are saying. 

Options:
- Impostors only hear other impostors when active, other players are muted
- Impostors can hear everyone even even when impostor radio is active
- Radio / muffled voice filter when used to indicate it's radio

**Describe alternatives you've considered**
This is a feature the among us mumble has.
https://github.com/StarGate01/AmongUs-Mumble

**Additional context**

**Comment by KadenBiel** [comment]
I was literally thinking about this last night. I think we're a bit more focused on translations right now, but I'll certainly add this once I have the chance.

**Comment by OhMyGuus** [comment]
Thanks for the idea
