### ISSUE TITLE
I can hear no one and no one hears me; `error: process_vm_readv`

### ISSUE THREAD

**Issue by deckk** [OhMyGuus/BetterCrewLink#129]
**Describe the bug**

I can hear no one and no one can hear me. BetterCrewLink opens up just fine, detects if the game is open or not, when it's in a lobby or not, lists the people and myself in the lobby in the overlay and the BetterCrewLink window, and detects when I am speaking -- but no one hears me and I can hear no one else. My BetterCrewLink detects when I am speaking indicated by the green circle but no one else's circles go green. I have tested my microphone and speakers.

**To Reproduce**
Steps to reproduce the behaviour:
1. `./BetterCrewlink-Linux.AppImage` (version 2.4.5)
2. Open Among Us in Steam (opening through BetterCrewLink results in Error Start the game manually. (this button is only for steam)
3. Join a lobby
4. Cannot hear anyone and no one hears me.

**Expected behaviour**

**Screenshots**

BetterCrewLink error when clicking the Open Game button
![image](https://user-images.githubusercontent.com/67703748/114242908-8cfba680-9983-11eb-972a-bb67feddd378.png)

**Desktop (please complete the following information):**
- Operating System: Manjaro Linux
  - Kernel Version: 5.11.10-1-MANJARO

**Additional context**

Tried Proton 5.13-6 and 6.3-2

Terminal output once Among Us opened, repeated for the whole time Among Us is opened. Stops when Among Us closed.
```
error: process_vm_readv returned -1 instead of 4 (Bad address) address=0x65f6db52 
error: process_vm_readv returned -1 instead of 4 (Bad address) address=0x200097f1 
error: process_vm_readv returned -1 instead of 4 (Bad address) address=0x2000817d 
error: process_vm_readv returned -1 instead of 4 (Bad address) address=0x65f6db52 
```

Everyone else in the lobby was on Windows and could all hear each other.

**Comment by OhMyGuus** [comment]
Can I ask if you saw any icons like wifi icons or yellow icons on top of the players?
And if not did u try to enable NAT FIX in the settings

**Comment by deckk** [comment]
No such icons.

NAT Fix worked! Thank you!
