### ISSUE TITLE
[FEATURE] Disable Prox Chat, Global Imposter Chat, etc

### ISSUE THREAD

**Issue by ryantheleach** [OhMyGuus/BetterCrewLink#14]
Crewlink and BetterCrewLink are really cool in the voice features they add to among us, and integrate better then discord auto muting solutions etc.

It would be great to see a mode which disables proximity chat, and only allows dead / meetings to talk.

In addition, maybe adding an option for global imposter chat?

**Comment by OhMyGuus** [comment]
Will add a option to do that, atm there is only a option to disable proxy for alive players.

**Comment by lanc3lo1** [comment]
Hey, I'm just here to report that I'm playing with my friends on BetterCrewLink 2.1.3 and I can't get "Hear people through cameras" I checked the option before game start and no sound through cameras in game, is that any known bug or something to set to make sure it'll work fine ?

**Comment by OhMyGuus** [comment]
Added!
