### ISSUE TITLE
[BUG REPORT] 32 bit install 

### ISSUE THREAD

**Issue by Ricoculous** [OhMyGuus/BetterCrewLink#15]
While 32bit install is available, it automatically installs the 64bit version. Is there a way to force 32 bit?

**Comment by OhMyGuus** [comment]
I don't have a 32bit virtual machine at the moment to try if 32 bit still works. But it should just install the 32 bit if you are on 32 bit. 
If it doesn't u can download the unpacked version of BetterCrewlink from https://mirror.bettercrewlink.app be aware you need to update that one manually. 

If that still doesn't work then can u message me on discord (ThaGuus#2140) or place a message in the discord so I can fix this easier.
