### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by lanc3lo1** [OhMyGuus/BetterCrewLink#16]
Hey, I'm just here to report that I'm playing with my friends on BetterCrewLink 2.1.3 and I can't get "Hear people through cameras" I selected the option before game start and no sound through cameras in game, is that any known bug or something to set to make sure it'll work fine ?

 - OS: Windows 10
 - Version: 2.1.3

**Additional context**
All People in the lobby got BetterCrewLink 2.1.3, no one can hear through cameras.

**Comment by OhMyGuus** [comment]
Done
