### ISSUE TITLE
[BUG REPORT] Listening to people on the cameras is not working

### ISSUE THREAD

**Issue by MatadorProBr** [OhMyGuus/BetterCrewLink#163]
# You MUST use this template or your issue will be deleted.

**Before reporting a bug, always look at the [wiki](https://github.com/OhMyGuus/BetterCrewLink/wiki/common-issues) or [FAQ](https://discord.gg/qDqTzvj4SH) in Discord Server that there usually has a solution for your bug**

**If your problem is with BetterCrewLink on your mobile or the web version, [click here](https://github.com/OhMyGuus/BetterCrewlink-mobile/issues) and make an issue there, if your problem is with BetterCrewLink on the PC, ignore that and continue with your bug report**

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
2. [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
3. [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
4. [X] I have used `Ctrl+R` on the BetterCrewLink app when I can't hear some people (this is a known issue)
5. [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
6. [X] I have a screenshot of any errors
7. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

**Describe the bug**
2 people went to Discord complaining that "Listening to people on the cameras" was not working on any maps (it seems), so I came to report the bug here, and the bug probably started when the new Airship update came out, which probably must have broken this option.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Activate 'Listening to people on cameras'
3. Go to 'Cameras'

**Expected behaviour**
It was for the person on the camera to hear the other person if they are on a camera.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 2.5.0]

**Additional context**
N/A

**Comment by JKohlman** [comment]
This could be a conflict between certain settings. One of the people had the following settings selected when they noticed the issue:
- Walls Block Audio
- Hear People in Vision Only
- Impostors Hear Dead
- Private Talk in Vents
- Comms Sabotage Disables Voice
- Hear Through Cameras

**Comment by OhMyGuus** [comment]
Fixed with commit #ca9982600dfa13332de51fb519464d563c5b53b0
