### ISSUE TITLE
[FEATURE] Mono-channel option

### ISSUE THREAD

**Issue by jonciaguillard** [OhMyGuus/BetterCrewLink#165]
Love Prox chat for Among Us, but our friend group has one person that is deaf in one ear. An option for Mono-channel would be very useful for people that can't use stereo audio.
* I know it should be possible to do this in Windows itself, but sometimes it doesn't work and many people just don't understand Windows settings. *

**Comment by MatadorProBr** [comment]
There is already an option to disable Mono-channel in BetterCrewLink, just go to the BetterCrewLink settings and disable the "Spatial Audio" option as shown in the screenshot below

![image](https://user-images.githubusercontent.com/71022656/115118580-3fca9680-9f7a-11eb-967f-ec3ff7926027.png)
