### ISSUE TITLE
[BUG REPORT] Hearing through cameras 

### ISSUE THREAD

**Issue by MichalLytek** [OhMyGuus/BetterCrewLink#17]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ ] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

I've enabled the fun feature of hearing through cameras but I've tested with my friend that it isn't working neither on Polus (when I see only the players in single camera) nor on the Skeld (when there're multiple camersa so it would be understandable.

I have enabled the "Walls block audio" feature so maybe it's conflicting with each other 🤔 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

Hear the players which are standing in the middle of the screen visible through cameras.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10
 - Version: [e.g. 1.1.5] Among us v2020.12.9s

**Additional context**

**Comment by OhMyGuus** [comment]
Thanks for this report, stupid mistake fixed in next update!

**Comment by OhMyGuus** [comment]
Fixed in 2.0.7, again thanks for this report!
