### ISSUE TITLE
[BUG REPORT] Walls block audio sometimes works incorrect

### ISSUE THREAD

**Issue by MichalLytek** [OhMyGuus/BetterCrewLink#18]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ ] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

Walls block audio in general works ok - when I don't see the other players behind the wall, I don't hear them.

However, on the Polus there's a fence around electric, and I've tested with my friend that it also blocks the audio.

I suspect it's because the best crewlink is just checking if player can pass, which is false in case of the fence.

On the other way, when impostor close the doors on Polus, I can still hear the player behind the doors, if it is inside my voice range. Same goes to the decontamination on Mira and doors on the Balcony.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

It should couple the proximity chat voice range with the visibility of the person. so behind the fence it should be hearable but behind closed doors - not. Tricky part would be the windows which are making narrow ray of visibility 🤔 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.1.5]

**Additional context**

**Comment by OhMyGuus** [comment]
Will look into it, this will be fixed in a later release than 2.0.7.

**Comment by OhMyGuus** [comment]
Doors still needs to be added, but the fence is fixed now.

**Comment by OhMyGuus** [comment]
Fixed!
