### ISSUE TITLE
The translation changes have been undone

### ISSUE THREAD

**Issue by lamjed001** [OhMyGuus/BetterCrewLink#186]
This commit https://github.com/OhMyGuus/BetterCrewLink/commit/6d4c3b349b1b3fa12f701f79ec8669449873b7c0 made undo changes in most of languages

**Comment by MatadorProBr** [comment]
Well I know that you are a Translator and you are not in Discord so I will explain, we decided to change some names of some parts and Crowdin took the old translation and ended up reverting the translation to the original file, I will check today the translations and see if someone translated for the new adaptation, I recommend joining in the [Discord](https://discord.gg/qDqTzvj4SH) to receive this news and mention me or DM me (Matador#2690) if you want the role.

**Comment by MatadorProBr** [comment]
The commit b5ded7a will fix this problem, if you have any other problem with missing translation words that have already been translated open this issue again or create another one, for now it is in another branch but in the next update it will be merged into the main branch and also for the next update
