### ISSUE TITLE
[FEATURE] Make a Discord button in BetterCrewLink app

### ISSUE THREAD

**Issue by MatadorProBr** [OhMyGuus/BetterCrewLink#188]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
2. [X] I have checked that someone else has not suggested this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)
3. [X] My feature request is not one of the **commonly suggested features**:
- iOS app (its already being development)

**Is your feature request related to a problem? Please describe.**
In the BetterCrewLink app have Twitch, Twitter and Donate buttons, and my serious idea to add a Discord button where it would take you to the official BetterCrewLink Discord server or ThaGuus profile on Discord (probably a very useless suggestion and with a very low priority)

**Describe the solution you'd like**
Add a Discord button on the BetterCrewLink app where it would take you to the official BetterCrewLink Discord or profile of [ThaGuus](https://discordapp.com/users/508426414387757057) on Discord 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JKohlman** [comment]
Addressed in 7154f76!
