### ISSUE TITLE
[BUG REPORT] Custom colors don't work on OBS overlay

### ISSUE THREAD

**Issue by RuiNtD** [OhMyGuus/BetterCrewLink#195]
**Describe the bug**
Custom colors added by mods, such as Town of Us, show up as red in the OBS overlay.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Better CrewLink settings
2. Copy the OBS  Browser Source URL at the bottom of settings
3. Paste the link into your browser
4. Enter a game of Town of Us and select a custom color

**Expected behaviour**
Custom colors show correctly in the OBS overlay.

**Screenshots**
![](https://ipfs.io/ipfs/QmcFAaNd9HsUXNrqwoEh2YPYyUithqhw2DGvp1y4qMzS9S?filename=AwjflmMyJj.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.6.0

**Additional context**

**Comment by MatadorProBr** [comment]
Duplicate of #47
