### ISSUE TITLE
[BUG REPORT] Polus map, cannot hear people at southwest cam

### ISSUE THREAD

**Issue by TheCopycat** [OhMyGuus/BetterCrewLink#20]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

When looking at the cameras in polus, we cannot hear people at the southeast cameras. All other works well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Polus cameras
2. Click on cameras
3. Select southwest cameras
4. Ask a friend to go to southwest camera location and speak

**Expected behaviour**
Hearing the friend speaking.

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.1.3

**Additional context**
- Tested on 2.1.3. 
- Did a bit of tweaking, and by observing the disposition I tried to figure out which coordinates to change.
- Changing the coordinates from -4.7, -22.73 to 4.7,-22,73 seems to solve the problem (tested with a local build).
- I did not submit a PR because I do not know how to verify that the coordinates are accurate.
- Checked the source, seems to still be relevant in 2.1.7.

**Comment by OhMyGuus** [comment]
Thanks will look into it, idk how I didn't notice this with testing properly did a CTRL + Z somewhere when I made it. 
Will be fixed in the next release!

**Comment by OhMyGuus** [comment]
Fixed in 2.1.8!

**Comment by TheCopycat** [comment]
Thank you very much :). I make sure to test that.
