### ISSUE TITLE
Kill button not working when using bettercrewlink

### ISSUE THREAD

**Issue by Preslav4oL** [OhMyGuus/BetterCrewLink#207]
# You MUST use this template or your issue will be deleted.

**Before reporting a bug, always look at the [wiki](https://github.com/OhMyGuus/BetterCrewLink/wiki/common-issues) or [FAQ](https://discord.gg/qDqTzvj4SH) in Discord Server that there usually has a solution for your bug**

**If your problem is with BetterCrewLink on your mobile or the web version, [click here](https://github.com/OhMyGuus/BetterCrewlink-mobile/issues) and make an issue there, if your problem is with BetterCrewLink on the PC, ignore that and continue with your bug report**

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
2. [ ] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
3. [x] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
4. [ ] I have used `Ctrl+R` and I activated `NAT Fix` on the BetterCrewLink app when I can't hear some people (this is a known issue)
5. [x] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
6. [x] I have a screenshot of any errors
7. [ ] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 2.4.0]

**Additional context**

https://dox.abv.bg/download?id=92597903f7#

**Comment by MatadorProBr** [comment]
Wait for OhMyGuus answer you since we already saw you on Discord and for what you said "looks" like a BetterCrewLink bug and he takes care of that part

**Comment by OhMyGuus** [comment]
Is this the first time having this issue since on the video you are not moving... If you don't move after u spawn u can't kill.

**Comment by MatadorProBr** [comment]
Open and close settings when you can't move maybe fix the issue?
Because I already suffered this bug with/without BetterCrewLink of not being able to walk and resolved opening and closing the settings

**Comment by Preslav4oL** [comment]
guys i fixed the bug when the imp cant kill it was from me i was the problem
if somebody else hosted the game it fixed

**Comment by Preslav4oL** [comment]
i forgot to try that
at least i fixed it
