### ISSUE TITLE
BetterCrewLink can't install

### ISSUE THREAD

**Issue by Koko37yt** [OhMyGuus/BetterCrewLink#213]
Well i launch the setup.exe and when the bar is half full it just closes the setup and deletes the setup :c

**Comment by MatadorProBr** [comment]
What antivirus you have?

**Comment by Koko37yt** [comment]
AVG free

**Comment by MatadorProBr** [comment]
Try disable the AVG or put the BCL in AVG Exceptions and if it doesn't work please join in [BCL Discord](https://discord.gg/qDqTzvj4SH) for faster and more accurate support

**Comment by JKohlman** [comment]
Closing. Very likely was AVG flagging BCL as a false-positive
