### ISSUE TITLE
[BUG REPORT] Among US Stops Responding

### ISSUE THREAD

**Issue by henryozen** [OhMyGuus/BetterCrewLink#233]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [ ] I have a screenshot of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

Not sure what causes this however BetterCrewLink has been causing mine and other's games to stop responding. Once closing BetterCrewLink, the game always instantly crashes so it leads me to believe the issue isn't within the game.

### Expected behavior

It happens at random so I have no clue.

### Desktop

- OS: [e.g. Windows 10]
- Version: [e.g. 2.7.2]

**Comment by JKohlman** [comment]
Soo pretty sure I figured this out today. Should be closed by #297. But also half resolved this a while ago by switching to URI launches by default.
