### ISSUE TITLE
[FEATURE] Platform/installation detection on Linux

### ISSUE THREAD

**Issue by JKohlman** [OhMyGuus/BetterCrewLink#237]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)
- [X] My feature request is not one of the **commonly suggested features**: iOS app (it's already being development)

### Is your feature request related to a problem? Please describe.

Currently Linux installations require Among Us to be started manually outside of BCL.

### Describe the solution you'd like

BCL should detect that an installation is present and give the option to open via steam

**Comment by JKohlman** [comment]
Hey @7RST1 if you want to take a look and re-implement your solution to this it should be good to go!

**Comment by 7RST1** [comment]
Opened pull request #260

**Comment by JKohlman** [comment]
Forgot to close this with merge I guess, whoops
