### ISSUE TITLE
[getting banned after killing someone as an imposter while using betterCrewlink app on the phone. It says we are hacking..is it because it thinks that crewlink is a third party app? Pls fix this issue

### ISSUE THREAD

**Issue by N01SE3** [OhMyGuus/BetterCrewLink#25]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.1.5]

**Additional context**

**Comment by OhMyGuus** [comment]
This is not a bettercrewlink/crewlink issue, this happends when your connection to Amng us is slow. The position the server has for you differs from the position of your client, this causes sometimes a kick/ban because it thinks you killed him from too far away.
