### ISSUE TITLE
[Bug/Feature] BetterCrewLink on Linux 

### ISSUE THREAD

**Issue by Donokami** [OhMyGuus/BetterCrewLink#26]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I have checked that someone else has not suggested this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
3. [x] My feature request is one of the **commonly suggested features** (but I've been approved): Linux / MacOS support

**Is your feature request related to a problem? Please describe.**
BetterCrewlink start on Steam Proton, but doesn't work correctly. There is no audio device/microphone, and Better Crewlink doesn't detect Among Us.
This issue is common to CrewLink, there is already an issue about that: https://github.com/ottomated/CrewLink/issues/4

**To Reproduce**
Steps to reproduce the behaviour:
1. Installing protontricks
2. Running `protontricks -c "wine /home/donokami/Downloads/Better-CrewLink Setup 2.2.3.exe" 945360`
3. After that it installs Better-Crewlink and start it.
4. It loops on this message :
![image](https://user-images.githubusercontent.com/5563277/107411826-4a4a5900-6b0f-11eb-962f-047f1ab5a138.png)
Interface is clickable. But "Open Game" doesn't open anything, and in settings, no audio device/microphone is found :
![image](https://user-images.githubusercontent.com/5563277/107412060-8978aa00-6b0f-11eb-841c-f3a979d2762f.png)

**Expected behaviour**
It should detect my microphone and audio devices, and also detect Among Us.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.1 LTS x86_64 
- Host: Lenovo ideapad 330-15ARR 
- Kernel: 5.4.0-65-generic 
- Proton version : 5.13

**Describe the solution you'd like**
It seems that @zbanks was able to fix this issue on an older Crewlink version (here is his fork: https://github.com/zbanks/CrewLink). Maybe his changes are mergeable?
See what is the fix: https://github.com/ottomated/CrewLink/issues/4#issuecomment-747182894
I tried it, and it works really well. To try it, after starting Among us on Steam Proton:
```
wget "https://github.com/zbanks/CrewLink/releases/download/v1.2.1/CrewLink-1.2.1.AppImage"
chmod +x CrewLink-1.2.1.AppImage

echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
./CrewLink-1.2.1.AppImage
```
EDIT: There is another fork which add these compatibility changes on the latest Crewlink version:
https://github.com/TheGreatMcPain/CrewLink

Here is proof of working:
![image](https://user-images.githubusercontent.com/5563277/107414494-5c79c680-6b12-11eb-966f-dc141ddc0d77.png)
![image](https://user-images.githubusercontent.com/5563277/107414545-72878700-6b12-11eb-8672-ab5881c42ec8.png)

**Additional context**
Proton is a Wine (Windows simulation) system for Linux systems, that makes Among Us working on it.

**Comment by TheGreatMcPain** [comment]
I do have a [branch in my fork called bettercrewlink-linux](https://github.com/TheGreatMcPain/CrewLink/tree/bettercrewlink-linux) which ports `BetterCrewLink` to Linux.

I only needed to port [node-keyboard-watcher](https://github.com/TheGreatMcPain/node-keyboard-watcher) (used for push-to-talk), because it used a Windows only function to check the state of the keyboard.  I personally haven't tested it yet, but at least it builds and allows `BetterCrewLink` to work on Linux.

**Comment by Donokami** [comment]
> I do have a [branch in my fork called bettercrewlink-linux](https://github.com/TheGreatMcPain/CrewLink/tree/bettercrewlink-linux?rgh-link-date=2021-02-10T16%3A15%3A47Z) which ports `BetterCrewLink` to Linux.
> 
> I only needed to port [node-keyboard-watcher](https://github.com/TheGreatMcPain/node-keyboard-watcher) (used for push-to-talk), because it used a Windows only function to check the state of the keyboard. I personally haven't tested it yet, but at least it builds and allows `BetterCrewLink` to work on Linux.

Pretty thanks! It works quite well on your latest PR @TheGreatMcPain, only the overlay doesn't work (I've got a white screen)

**Comment by TheGreatMcPain** [comment]
Like i said in my pr.  There are fixes that i need to add which fix the overlay transparency.

**Comment by JKohlman** [comment]
Can probably close as the linux repo has been moved to being worked on [here](https://github.com/OhMyGuus/BetterCrewlink-Linux)

**Comment by MatadorProBr** [comment]
Linux support is now in this repo and working, if there are any issues with it you can make an issue on this repo now.

https://github.com/OhMyGuus/BetterCrewLink/wiki/installation#linux

**Comment by OhMyGuus** [comment]
Thanks a lot TheGreatMcPain and @Donokami  btw with helping us with all of the investigation and forks 👯
