### ISSUE TITLE
[BUG REPORT] Impostor radio sound plays even when setting is turned off

### ISSUE THREAD

**Issue by JKohlman** [OhMyGuus/BetterCrewLink#262]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [X] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

The impostor radio sound plays even when setting is turned off when the key is pressed

### Steps to reproduce the behavior

1. Disable impostor radio
2. Spawn as impostor
3. Press the impostor radio hotkey

### Expected behavior

No sound should play

### Desktop

AU 6.30s

**Comment by OhMyGuus** [comment]
Fixed
https://github.com/OhMyGuus/BetterCrewLink/commit/da8b14ff3332ccc1c06c412470b06825b25a0aa3
