### ISSUE TITLE
[BUG REPORT] Black Screen on reload when Overlay is enabled

### ISSUE THREAD

**Issue by Jaydewhisker** [OhMyGuus/BetterCrewLink#27]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
When clicking the reload button while the Overlay is enabled, Among Us goes black until the overlay is disabled/unchecked. Once you re-enable the overlay, it does not black screen on reload anymore, until you change the overlay settings, such as position, in which case it will re-black screen on reload.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to BetterCrewLink
2. Click on the reload button while the overlay is enabled
3. Among Us screen is now black

**Expected behaviour**
This shouldn't happen

**Screenshots**
![4lAJNYxBEo](https://user-images.githubusercontent.com/45524386/107434426-c71e0880-6af8-11eb-93b4-711789e8d93d.png)

**Desktop (please complete the following information):**
 - OS Windows 10
 - Version: 2.2.3

**Additional context**

**Comment by OhMyGuus** [comment]
We noticed this bug on some devices, is fixed in next update, which is
currently in testing. If u want u can test it yourself as well if it is
actually fixed.

https://mirror.bettercrewl.ink/beta

**Comment by OhMyGuus** [comment]
Should be resolved in 2.2.5, if not reopen this issue!
