### ISSUE TITLE
[BUG REPORT] 

### ISSUE THREAD

**Issue by reneclaus** [OhMyGuus/BetterCrewLink#273]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [X] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

Crewlink stopped sending mic audio. The mic sensitivity bar stilled showed the audio and the mic worked fine in Discord.

In the end I was able to resolve the issue by unchecking the "Microphone Sensitivity" checkbox.

Things that didn't work:
* restarting crewlink
* restarting the computer
* changing the sound settings in windows
* Changing the mic mode--Voice Activity, Push to Talk, Push to Mute

I suggest that the "Common Issues" section suggest turning off the "Microphone Sensitivity" checkbox if the mic doesn't seem to be working
![Untitled](https://user-images.githubusercontent.com/1834172/137247842-1fda6300-efd2-4609-9b28-75de56fa934d.png)
.

### Steps to reproduce the behavior

1. Turn on "Microphone Sensitivity"
2. Maybe needs multiple microphones on the computer (such as Bluetooth headphones)

### Expected behavior

The character should light up when I talk and other people should hear me.

### Desktop

Windows 10
The computer had both the built in microphone and a bluetooth heads.

**Comment by MatadorProBr** [comment]
Maybe I will add this, it's just going to take a while because I'm having some personal issues and I don't plan on touching the wiki yet

**Comment by OhMyGuus** [comment]
Issue is a non issue, the value of his sens is way to low
