### ISSUE TITLE
[BUG REPORT] Screen is going black when Overlay is enabled.

### ISSUE THREAD

**Issue by adrenblast** [OhMyGuus/BetterCrewLink#28]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [X ] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [X] I have checked everyone in my lobby is on the same CrewLink server
5. [X] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [X] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...' Settings
2. Click on '....' Enable Overlay

**Expected behaviour**

It usually takes less than a minute, but the screen goes black. Turning off overlay allows it to work again.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10
 - Version: [e.g. 1.1.5] Version 2.2.5

**Additional context**

**Comment by OhMyGuus** [comment]
Is this after a refresh or is this from the start?

**Comment by qexat** [comment]
Hi, using EndeavourOS 5.18.10-arch1-1 (64-bit) with BetterCrewLink 3.0.1, it seems that a similar bug happens to me. A black rectangle covers all the screen when the overlay is activated.

**Comment by sfxworks** [comment]
Occurring on 5.15.91-1-MANJARO 
There's a black rectangle. When I move to window mode you can see the black screen catch up when I let go of the mouse

**Comment by salamturk** [comment]
> Hi, using EndeavourOS 5.18.10-arch1-1 (64-bit) with BetterCrewLink 3.0.1, it seems that a similar bug happens to me. A black rectangle covers all the screen when the overlay is activated.

yea i am having this issue
