### ISSUE TITLE
[BUG REPORT]  Cant hear during games

### ISSUE THREAD

**Issue by Smario9000** [OhMyGuus/BetterCrewLink#294]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [ ] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

we can hear people when in lobby or in meetings but not during games and it is setup to hear people during games

### Steps to reproduce the behavior

just start a game and test if you can hear people

### Expected behavior

to be able to hear people during games

### Desktop

- OS: [e.g. Windows 10]
- Version: 2.9.6

### Additional context

thanks

**Comment by JKohlman** [comment]
What version of the game are you running? What are the lobby settings? If you're able to join the discord that is the best place to find results. Also have you tried enabling NAT Fix?

**Comment by Smario9000** [comment]
game version 2022.2.24s with Town of us v 2.6.5
better crew link settings 
 - walls block audio
 - imp hear dead
 - private talk in vents
 - comms disable voice
 - hear cameras
 - imp radio

no i am not a part of your discord need link
never had to use nat fix but i can try next time

**Comment by MatadorProBr** [comment]
You can join in the Discord via this link: https://discord.gg/qDqTzvj4SH so we can help you better and more fast.

**Comment by Smario9000** [comment]
also the 2.9.7 fixes this problem thanks
