### ISSUE TITLE
[BUG REPORT] BetterCrewLink can't find my audio devices, but CrewLink can.

### ISSUE THREAD

**Issue by aryairani** [OhMyGuus/BetterCrewLink#30]
CrewLink (tag: v.2.0.1)           |  BetterCrewLink (tag: v.2.2.5)
:-------------------------:|:-------------------------:
![CrewLink-audio](https://user-images.githubusercontent.com/538571/107601064-98388d00-6bf3-11eb-870d-c070e208e26d.png) | ![BetterCrewLink-no-audio](https://user-images.githubusercontent.com/538571/107601076-9d95d780-6bf3-11eb-9c51-1fd6c5dd5690.png)

**Desktop (please complete the following information):**
OS: Windows 10 Pro Insider Preview
Version: 2004
OS build: 21286.1000
System type: 64-bit operating system, ARM-based processor

**Comment by OhMyGuus** [comment]
Very weird, there shouldn't be much difference for this between our version and original crewlink tbh. 

Only thing I can think of at the moment is that this function is fucking up.

https://github.com/OhMyGuus/BetterCrewLink/blob/f16d8827a11d6ddc537dc933c34386892f747bae/src/main/index.ts#L256

If u uncomment that it might work

**Comment by aryairani** [comment]
Hmm, I didn't understand what to try — isn't that already uncommented?

**Comment by OhMyGuus** [comment]
I ment comment out so add // before the lines
256 until 268

**Comment by OhMyGuus** [comment]
https://mirror.bettercrewl.ink/beta/Better-CrewLink%20Setup%202.2.0.exe

**Comment by aryairani** [comment]
I'm downloading it now.  Do you think I'll run into the same 64-bit memory.js / ARM issue with that installer?

I did try commenting out 256–268 and then `yarn dev` with  no change.

**Comment by aryairani** [comment]
With that installer, it does detect my audio devices 🎉 , but (like we previously talked about) doesn't detect Among Us.

**Comment by OhMyGuus** [comment]
Oh forgot that you are on arm xD

**Comment by aryairani** [comment]
I'm still having this issue with the latest release. CrewLink 2.0.1 works fine, BetterCrewLink 2.3.5 can't detect my audio devices.

**Comment by aryairani** [comment]
Commenting out that block you suggested above doesn't help though.

**Comment by aryairani** [comment]
@OhMyGuus It seems to have been this commit that broke it for me 60fdff4ece1131148f86a53a769dd2308aac34cb.

**Comment by mjeveritt** [comment]
> @OhMyGuus It seems to have been this commit that broke it for me [60fdff4](https://github.com/OhMyGuus/BetterCrewLink/commit/60fdff4ece1131148f86a53a769dd2308aac34cb).

That looks an interesting commit to bisect ... :joy:

**Comment by aryairani** [comment]
It's just the `electron` version update; v9.x worked; v10.x, 11.x, 12.x didn't.

**Comment by aryairani** [comment]
I can create a PR to switch to electronjs 9.4.4, but since 9.x recently is EOL, I'm not sure it would or should be accepted.  However, I wish the bug report could be submitted to electronjs by someone who knows enough about electronjs to do it.  (i.e. not me)

**Comment by mjeveritt** [comment]
Gotcha, thanks for the insights, @aryairani . Agreed that fixing whatever issue presents in electron >= 10 is the way forward, alas I'm just as lost as you where this code is concerned! :grin:

**Comment by aryairani** [comment]
In the mean time though, I have to build BetterCrewLink from source with electron 9.4.4 to be able to run it :-\  Would be great if I didn't have to.

**Comment by aryairani** [comment]
I can help with putting together a ticket for electron or chromium, but am not knowledgeable enough to do it without help.  Feel free to ping me here or on Discord to coordinate.

**Comment by aryairani** [comment]
With 
```
Parallels Desktop Version 16.5.0 (50692)
Microsoft Windows 10 Pro v10.0.21376 (21376)
```
I don't have the issue anymore on v2.6.4 or even the original v2.2.5, so I'm closing the issue.

**Comment by aryairani** [comment]
Also, the 64-bit version seems to run for me now; no more `yarn dist:32` or custom builds with auto-updates disabled. 🎉 🤞
