### ISSUE TITLE
Other Roles Neutral Roles not hearing crew outside of meetings [BUG REPORT] 

### ISSUE THREAD

**Issue by davisa6477** [OhMyGuus/BetterCrewLink#311]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [ ] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

When playing in The Other Roles mod, neutral roles are unable to hear the crew while on the map, but can hear the crew while in meetings. Those roles can be heard by the crew.

### Steps to reproduce the behavior

Play a game in The Other Roles mod with BCL and have a neutral role try to communicate.

### Expected behavior

All roles should be able to hear each other.

### Desktop

- OS: Windows 10
- Version: 3.0.2

**Comment by OhMyGuus** [comment]
Tested it and can't seem to reproduce this.... :| 
Are u able to create an ticket in our discord so we can get a bit more info about it?

https://discord.gg/qDqTzvj4SH

**Comment by JKohlman** [comment]
Resolved with latest patches, should work in next release
