### ISSUE TITLE
[FEATURE] Publish releases to Windows Package Manager (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal9** [OhMyGuus/BetterCrewLink#313]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)
- [X] My feature request is not one of the **commonly suggested features**: iOS app (it's already being development)

### Is your feature request related to a problem? Please describe.

It is difficult to keep manifests updated on WinGet with every new release of BetterCrewLink.

### Describe the solution you'd like

With every new release of BetterCrewLink, use a GitHub workflow that will trigger on every GitHub release and update the manifests at https://github.com/microsoft/winget-pkgs repository.

### Describe alternatives you've considered

N/A

### Additional context

I can create a pull request if you would like.

**Comment by MatadorProBr** [comment]
If you have a repository that checks and make automatically PR's to https://github.com/microsoft/winget-pkgs, why we should make a GH workflow that basically makes the same thing but with another GH account?

**Comment by JKohlman** [comment]
> If you have a repository that checks and make automatically PR's to https://github.com/microsoft/winget-pkgs, why we should make a GH workflow that basically makes the same thing but with another GH account?

I believe what is happening currently is that @vedantmgoyal2009 is manually triggering/making a PR for winget on every single release we do but would like for us to have a workflow which automatically does this when we release BCL. Is that correct Vedant?

**Comment by vedantmgoyal9** [comment]
I do  have a repository for automation but I'm asking developers to automate publishing from their side because of 2 reasons:
- Microsoft prefers developers to manage releases for their applications themselves. They allow, but usually don't prefer a 3rd party to control someone's else application in the community repository. Exceptions are the non-GitHub apps which have a release API so that we can fetch update information and update the manifests accordingly.
- It is also getting hard for me to maintain a vast (~1000) number of packages in the automation due to insufficient time and higher studies.

**Comment by OhMyGuus** [comment]
> I do have a repository for automation but I'm asking developers to automate publishing from their side because of 2 reasons:
> 
> * Microsoft prefers developers to manage releases for their applications themselves. They allow, but usually don't prefer a 3rd party to control someone's else application in the community repository. Exceptions are the non-GitHub apps which have a release API so that we can fetch update information and update the manifests accordingly.
> * It is also getting hard for me to maintain a vast (~1000) number of packages in the automation due to insufficient time and higher studies.

I'm fine with adding a action for this, do u know if there are already some templates for this (maybe from other electron apps)?

**Comment by vedantmgoyal9** [comment]
@OhMyGuus I've created a pull request.

> do u know if there are already some templates for this (maybe from other electron apps)?

I'm not much familiar with electron-builder, so don't know about this. Sorry 🙏🏻
