### ISSUE TITLE
[BUG REPORT] Occasionally can not hear people during tasks while using TOR

### ISSUE THREAD

**Issue by JKohlman** [OhMyGuus/BetterCrewLink#314]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [X] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

While using The Other Roles mod sometimes users stop hearing voice chat during the tasks stage of the game. This does not appear to effect meetings and/or lobbies.

It has been observed with neutral and crewmate roles across 3 different groups of people.

Roles:
- Medic
- Lawyer
- Jackal
- Lover Seer

BCL Settings when user 1 encountered:
- Walls Block Audio
- Impostors Head Dead
- Private Talk in Vents
- Comms Sabotage Disables Voice
- Hear Through Cameras
- Impostor Radio

### Steps to reproduce the behavior

Have not been able to reproduce reliably yet.

### Expected behavior

Voice should work in the tasks stage for all players.

### Screenshots/Videos

Placeholder for later

### Desktop

- OS: Windows 10
- BCL Version: 3.0.2

**Comment by OhMyGuus** [comment]
Should be fixed now
