### ISSUE TITLE
[BUG REPORT] 3.0.2 and 3.0.3 immediately exit with "FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable."

### ISSUE THREAD

**Issue by keithzg** [OhMyGuus/BetterCrewLink#315]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [X] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

As of 3.0.2 and 3.0.3, the AppImage immediately exits like so:

```
CONFIG count:  26
Checking for update
Opened app version:  3.0.3
[1144195:0626/212451.962581:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

3.0.1 works fine, other than that it auto-downloads 3.0.3 and deletes the AppImage every time, which is inconvenient ;)

### Steps to reproduce the behavior

Happens immediately upon launch, error message visible if started from a terminal.

### Expected behavior

Like 3.0.1, it should actually launch :)

### Desktop

- OS: Kubuntu 22.04
- Happens whether game is open or not

### Additional context

I can reproduce this on a system running an AMD Radeon 5500XT and another with Intel built-in graphics, both running Kubuntu 22.04. 

Conversely, on a *buntu 20.04 system (in an Openbox session) 3.0.3 launches just fine . . .

I can try additional distros and releases to try and nail down the repro conditions a bit more if this info so far isn't enough to point to the culprit!

**Comment by OhMyGuus** [comment]
We are aware that some gpu drivers on Linux are causing this error, we implemented a fix for it in 3.0.1 (updating to the latest chromium/electron version). 
Sadly this fix gave us multiple tickets that the overlay wasn't working anymore by some people (and we couldn't figure out why) so we had to revert it. 

Now there maybe another option to fix it but I have no idea how well that works, which is adding "--disable-gpu-sandbox" to the startup command.

**Comment by OhMyGuus** [comment]
I also would like u to try this version it added the disable-gpu-sandbox switch in code: 
https://github.com/OhMyGuus/BetterCrewLink/pull/316#issuecomment-1167239923

**Comment by keithzg** [comment]
Funny enough the overlay has never worked quite right for me on this PC so I had it disabled anyways (I run Among Us in a window, and the overlay is sized and centered wrong).

With both the `--disable-gpu-sandbox` flag and running the AppImage attached to that PR, BetterCrewLink launches just fine! I tested it in a public lobby and everything worked fine for me (with the exception of the overlay, which is screwy but in exactly the same way it's always been for me, so disable-gpu-sandbox doesn't appear to have cause any problems).

**Comment by OhMyGuus** [comment]
Thanks for testing! Merged my fix and will be released fully in the next update
