### ISSUE TITLE
Custom color support

### ISSUE THREAD

**Issue by Snowad14** [OhMyGuus/BetterCrewLink#32]
Some mods on among us (BepInEx) client-side add new colors (example my mod: https: //github.com/Snowad14/Mores-Colors) but this one bugged bettercrewlink, if you could add that it would be nice cool, thanks

**Comment by OhMyGuus** [comment]
I know this issue is made a bit ago, but is added in the next update. Thanks for the request tho.

**Comment by RedLightning42** [comment]
Fixed in 2.3.5 but not on the OBS overlay
