### ISSUE TITLE
[FEATURE] Reverse PTT (Push to Mute)

### ISSUE THREAD

**Issue by RedLightning42** [OhMyGuus/BetterCrewLink#33]
So I like Push to Talk for streaming, but I can't find a key that works with my usual play style, so I was wondering if you could add Push to Mute so I can hold a key to talk to chat, but release to keep talking under Voice Activity mode.

Thanks!
Brian

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ ] I have checked that someone else has not suggested this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)
3. [ ] My feature request is not one of the **commonly suggested features**:
- Adjustable voice radius
- Mobile support
- Linux / MacOS support
- Itch.io support

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JKohlman** [comment]
Sounds like a good idea, I implemented it and submitted a pull request!

**Comment by OhMyGuus** [comment]
Added in next version of BetterCrewlink, Thanks for the request @RedLightning42 and thanks for the pr @JKohlman

**Comment by RedLightning42** [comment]
Thanks guys! Can't wait to try it out! Keep up the good work!
