### ISSUE TITLE
Problem with bettercrewlink sound 

### ISSUE THREAD

**Issue by Desleholmes** [OhMyGuus/BetterCrewLink#34]
Hey
I have a problem with BetterCrewlink, when I log in to the game, I can't hear anyone and no one can hear me. Even if I do crtl R, it does not work, I have an icon with a WiFi logo barred and orange ... i tried 3 different networks: WiFi, 4g and 5g, and it didn't change anything m
What's the problem?
Before, I played on Crewlink, and it worked :/
Thanks

**Comment by OhMyGuus** [comment]
Sorry for the late response but you should try to enable NAT FOX in settings (above change voice server

**Comment by Desleholmes** [comment]
Sorry, i just tried, and this isn't work too :/

**Comment by aryairani** [comment]
@OhMyGuus Is there a reason not to enable NAT FIX for everyone?

**Comment by JKohlman** [comment]
@Desleholmes perhaps you need to allow better crewlink through your firewall?

**Comment by Desleholmes** [comment]
> @Desleholmes peut-être avez-vous besoin d'autoriser un meilleur crewlink à travers votre pare-feu?

IDK how to do that :')

**Comment by OhMyGuus** [comment]
https://discord.gg/qDqTzvj4SH

Didn't check the issue for a long time if it is still not fixed contact us on the discord.
