### ISSUE TITLE
[BUG REPORT]  The Github/Discord/Support icons at the bottom of the window block player icons and the ability to right click interact with them (i.e. volume changes, etc)

### ISSUE THREAD

**Issue by Awsomonium** [OhMyGuus/BetterCrewLink#342]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [X] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

Among Us is Steam version

On the Better Crew Link window where it displays the icons of the those in your lobby, you're meant to be able to click on those icons to access a volume options popup. This popup contains the volume slider. 

However, the Github/Discord/Support icons at the bottom of the Better Crew Link window obscure the icons of the player on the bottom row. 

For an example, please refer to the image attached to the below screenshots/videos section. I used Photoshop to show what I mean as I did not have a screenshot on hand to show it.

 

### Steps to reproduce the behavior

1. Go to Better Crewlink Window while a game is active with 4 or more other players.
2. Click on lower row of player icons.
3. Notice that it's very difficult to do so, as Github/Discord/Support icons are in the way.

### Expected behavior

Expected behavior is that it should be easy to click on the icons of the players.

### Screenshots/Videos

![BetterCrewLink - edited](https://user-images.githubusercontent.com/16411824/196833698-46e8669d-394c-41b3-ae38-e3136ad1fd5f.png)

### Desktop

- OS: Windows 10
- Version: Current Among Us Version - Steam Build ID: 9624906
-BetterCrewLink Version: 3.0.5

### Additional context

Apologies if it's been reported. I did search, but I closest I could find was a request to be able to resize the window.

**Comment by OhMyGuus** [comment]
![image](https://user-images.githubusercontent.com/12090928/196836647-b45decba-9f91-4fe7-b17c-c0c5ae5b08ad.png)
It should look like this when u have 7 players in the game for me it's still fine to adjust the volume & as soon as u hit 8 players it will hide those buttons like this: 
![image](https://user-images.githubusercontent.com/12090928/196836876-ec1d7b6f-885a-4b90-8311-bcba1603f94c.png)

If it doesn't look like that for u then we need a screenshot

**Comment by Awsomonium** [comment]
It does not look like that for me, I'll get one next time I play with my group.

**Comment by OhMyGuus** [comment]
> It does not look like that for me, I'll get one next time I play with my group.

Most likely your name is too long which causes a bug at the moment (will be fixed soon)

**Comment by JKohlman** [comment]
@Awsomonium you can download the windows installer from the comments in PR #343 with the fix until it is pushed as a release!
