### ISSUE TITLE
[BUG REPORT] I am able to hear everyone communicate anywhere on the map 

### ISSUE THREAD

**Issue by mkyuhan** [OhMyGuus/BetterCrewLink#352]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [X] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

I was playing among us using bettercrewlink then all of a sudden everyone in game including myself has a red circle with an exclamation point on them. This resulted in hearing everyone communicate regardless of where they were on the map. 

### Expected behavior

Only be able to hear people nearby me.

### Screenshots/Videos

![Screenshot (26)](https://user-images.githubusercontent.com/119995294/206085393-d4fddc80-423e-48ab-90fe-f3753a68c18b.png)

### Desktop

Windows 10
Intel iRiSxe
10.0.1

**Comment by McBlob** [comment]
Same problem

**Comment by MatadorProBr** [comment]
Do you installed some mod recently?

**Comment by McBlob** [comment]
Forgot to tell fixed it by deinstalling among us and removing any leftover files from previous modding.
