### ISSUE TITLE
[BUG REPORT] 

### ISSUE THREAD

**Issue by CharCharthemonkey** [OhMyGuus/BetterCrewLink#353]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [ ] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

updated to 3.1.1 and could hear no1 in better crewlink at all so pls fix also tried everything listed in issue 34 that didnt work for me so pls help

### Steps to reproduce the behavior

update to 3.1.1
nothing
nothing
no sound from anyone

### Expected behavior

open bettercrewlink and 0 issues pls

### Desktop

- OS: [e.g. Windows 10] windows 10
- Version: [e.g. 2.7.2]
![image](https://user-images.githubusercontent.com/30783285/210592345-3656b924-5f25-40b9-be93-147184f8a76a.png)

**Comment by CharCharthemonkey** [comment]
also i just joined the better crewlink discord so feel free to ping me if info is needed cause i want this fixed pls

**Comment by MatadorProBr** [comment]
> also i just joined the better crewlink discord so feel free to ping me if info is needed cause i want this fixed pls

What is your username? Since it's more easy to help on Discord
but if you don't want, here is probably the fix: Try enabling NAT Fix on the BetterCrewLink settings

**Comment by CharCharthemonkey** [comment]
CHarliepratt#6393 on discord and tried that b4 but no luck then saw someone else posted the exact issue and one of the devs said it might of been on yalls end so idk
