### ISSUE TITLE
[BUG REPORT] ERROR: Error: unable to find module

### ISSUE THREAD

**Issue by Kyr4l** [OhMyGuus/BetterCrewLink#357]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [X] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

started BCL from the appimage file, once the game is started i immediately got a console error
i've tried older versions such as 3.1.0 and 3.1.1, these AppImages don't even run, they aren't recognized as executable files
3.1.2 is the only version that launches among the recent AppImages, but that's all it does

strace:
```
ERROR: Error: unable to find module
    at findModule (/tmp/.mount_BetterBdbFX3/resources/app.asar/node_modules/memoryjs/index.js:87:23)
    at GameReader_GameReader.checkProcessOpen (/tmp/.mount_BetterBdbFX3/resources/app.asar/webpack:/src/main/GameReader.ts:100:26)
    at GameReader_GameReader.loop (/tmp/.mount_BetterBdbFX3/resources/app.asar/webpack:/src/main/GameReader.ts:154:16)
    at Timeout.frame [as _onTimeout] (/tmp/.mount_BetterBdbFX3/resources/app.asar/webpack:/src/main/hook.ts:116:33)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

### Steps to reproduce the behavior

1. Open BCL AppImage
2. Start the game
3. That's it

### Expected behavior

I should be able to view the comms interface

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/24955106/233929276-6caa56c2-87a5-409c-a74a-790f06b194d8.png)

### Desktop

- OS: OpenSUSE TumbleWeed

**Comment by pamymaf** [comment]
@Kyr4l Did you ever get this working? I have the same error after a different install/run method. I am using flatpak Steam on NixOS. I told Among Us to use Proton 8 and then told Steam to open a cmd in the prefix. From there I opened Among Us and then BCL and instantly get this same error.

**Comment by Kyr4l** [comment]
> @Kyr4l Did you ever get this working? I have the same error after a different install/run method. I am using flatpak Steam on NixOS. I told Among Us to use Proton 8 and then told Steam to open a cmd in the prefix. From there I opened Among Us and then BCL and instantly get this same error.

The latest appimage works as expected
