### ISSUE TITLE
[BUG REPORT] Static noise when I join a game with bcl

### ISSUE THREAD

**Issue by Devious7** [OhMyGuus/BetterCrewLink#371]
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [ ] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

Whenever I join a game while I have bcl and other people are talking, all of my audio is corrupted, most of the time their are loud static noises and white noise playing then sometimes the audio will entirely bug out and stop working for a few seconds, this even impacts audio outside of the game like music im listening to. My microphone also stops working whenever this happens.

### Steps to reproduce the behavior

there werent really any steps, suddenly bcl just started to have static noises whenever I joined games around september or so

### Expected behavior

Usually when I join a vc game their isnt static noises and the audio works just fine and my mic should work.

### Desktop

- OS: [e.g. Windows 10]
- Version: [3.1.3]

**Comment by penguinwokrs** [comment]
@Devious7 
It seems this issue has been closed, but is there a solution?
I am experiencing the same issue in BCL using a Razer BlackShark V2 X USB headset.
