### ISSUE TITLE
[BUG REPORT] Avatars don't generate when BetterCrewLink is opened before Among Us

### ISSUE THREAD

**Issue by JKohlman** [OhMyGuus/BetterCrewLink#39]
I was taking a look at some of the new code and ran with Among Us but noticed that sometimes I'd get broken links in the avatars displayed. After investigating some more it seems to be that the "generated" folder isn't created unless Among Us running at the time that BetterCrewLink is opened.

This happens when you have no generated folder and run BetterCrewLink THEN run Among Us
https://imgur.com/a/Eew60Er

Running Among Us first results in the folder being generated and everything working as intended.

Tested on commit 2943878 with `yarn dev`

**Comment by OhMyGuus** [comment]
Fixed
