### ISSUE TITLE
[FEATURE] Open Microsoft Store version using the open game button

### ISSUE THREAD

**Issue by ToraxOutlaw** [OhMyGuus/BetterCrewLink#40]
Downloaded the recently updated version, it still won't open the microsoft version, it still keeps trying to open the Steam version.

**Comment by Sebast04** [comment]
try opening the game first and then start better crewlink, it should link automatically, when I play Among Us with Mods and Proximity it works, if I wouldn't it would start the game normaly. But I dont have any experience with microsoft versions, maybe its not compatible.

**Comment by JKohlman** [comment]
This has been implemented and can be closed!
