### ISSUE TITLE
[BUG REPORT] Saving of Audio device doesn't work. 

### ISSUE THREAD

**Issue by OhMyGuus** [OhMyGuus/BetterCrewLink#41]
^^

**Comment by tomtom7157** [comment]
hello, i have a problem with your software.
I am using VoiceMeeter Potato at 48000 Hz. Software has chirps when you speak, do you already have the problem and do you have a solution?

**Comment by RedLightning42** [comment]
Yeah, I noticed this at one point, but looks fixed now?
