### ISSUE TITLE
Added support for Town of Us [FEATURE]

### ISSUE THREAD

**Issue by davisa6477** [OhMyGuus/BetterCrewLink#42]
Support for extra colors so that crewlink can recognize them and do the overlays properly.

**Comment by OhMyGuus** [comment]
It is in the works will be released today/tomorrow if you want to test it right now u can use the beta that I build 2 days ago: 
https://mirror.bettercrewl.ink/beta/Better-CrewLink%20Setup%202.3.0.exe

Be aware it is a beta it is not the full new release so it doesn't support the rainbow colors yet.

**Comment by davisa6477** [comment]
This works great!!! The rainbow one doesn't bother me, but I'm glad to have the overlays back in the game.

**Comment by OhMyGuus** [comment]
Support added in the latest update forgot to notify.

**Comment by susman2** [comment]
man im tryna find town of imposters but i cant find it :(

**Comment by MatadorProBr** [comment]
> man im tryna find town of imposters but i cant find it :(

The latest version of BetterCrewLink supports the Town Of Impostors too
