### ISSUE TITLE
[BUG REPORT] The new among us update has made it so that better-crewlink doesn't detect we're in a game.

### ISSUE THREAD

**Issue by Lapotate56** [OhMyGuus/BetterCrewLink#45]
Hello,

The new maj on among us destroyed better crewlink when we do Ctrl+r nothing happend

///
The new among us update has made it so that better-crewlink doesn't detect we're in a game.

**Comment by Cobbrou** [comment]
Yeah you right, you need to wait @OhMyGuus to fix it

**Comment by OhMyGuus** [comment]
Sorry what is the issue? Can u explain

**Comment by ErwanLeroux** [comment]
There was an update to Among Us, and now Better cewlink doesn't seems to detect lobbies anymore

**Comment by Lapotate56** [comment]
yes @ErwanLeroux has right, there is no ppl

**Comment by franckdrion** [comment]
Please fix it :'( thank youuu

**Comment by Soryuk** [comment]
Yes please ! thansk for your job

**Comment by piermitch** [comment]
You're the best @OhMyGuus we love you

**Comment by OhMyGuus** [comment]
Sorry for the delay here is a temp fix: 
https://mirror.bettercrewl.ink/beta/Better-CrewLink%20Setup%202.3.2.exe

**Comment by ErwanLeroux** [comment]
Seems like it's detecting lobby again, well done.

**Comment by OhMyGuus** [comment]
Everything should work fine again with the new update, have fun all 👍
