### ISSUE TITLE
[BUG REPORT] 2.3.5 Fixed Custom Colors, but not in the OBS Overlay

### ISSUE THREAD

**Issue by RedLightning42** [OhMyGuus/BetterCrewLink#47]
Customs Colors still break the OBS Overlay, easy as that... The latest 2 versions have Custom Colors working, but when you're using OBS Overlay, it shows them all as Red, and when you get to a Meeting, the OBS Overlay just fails and stays missing.

**Comment by JKohlman** [comment]
Is this still going on for you?

**Comment by OhMyGuus** [comment]
> Is this still going on for you?

Yes this issue is still not fixed, still need to send the colors to the obs overlay correctly

**Comment by RedLightning42** [comment]
I haven't played with extra colors for awhile, so can't personally confirm, but seems like it wasn't fixed yet...

**Comment by JKohlman** [comment]
If someone links the mod(s) I can try and look into this after the Among Us update when I get time

**Comment by OhMyGuus** [comment]
Temp fix for this is to add 
&mod=TOWN_OF_US
or 
&mod=TOWN_OF_IMPOSTORS
or 
&mod=OTHER_ROLES

for example:
https://obs.bettercrewlink.app/?compact=0&position=bottom_left&meeting=1&secret=XXXXXX&server=https://bettercrewl.ink&mod=TOWN_OF_US


In the next BCL update this will be automatic

**Comment by MatadorProBr** [comment]
I haven't tested it yet but I think this problem has been fixed since the new version has already come out and as OhMyGuus said above that in the next version it would be fixed, I will close this issue but if you continue to have these problems open the issue again
