### ISSUE TITLE
Some nice feature to add

### ISSUE THREAD

**Issue by Kusae** [OhMyGuus/BetterCrewLink#5]
1: Disable voice chat when comms are sabotaged
2: You can hear players when on cameras
3: Add a topleft/right option for overlay
4: When impostor are in the vent they can talk to each other but crewmate cant hear them

**Comment by Zettexe** [comment]
I think hearing players while on cameras would be a bit overpowered

**Comment by OhMyGuus** [comment]
All features are implemented, except 4. Which is currently diffrent because of crossplay. Might add an extra option for imposters only.

**Comment by Kusae** [comment]
> All features are implemented, except 4. Which is currently diffrent because of crossplay. Might add an extra option for imposters only.

I saw this feature in the latest version or we aint talking about the same thing?
Or did u make it that ppl hear impostor in vent?

**Comment by MichalLytek** [comment]
It would be handful to have a checkbox for making proximity chat working coupled with the vision. So if player has 0.75x, the voice range will be tuned to silent players outside of the vision range. Same goes to walls and doors.

**Comment by OhMyGuus** [comment]
All features including the one requested by @MichalLytek implemented !
