### ISSUE TITLE
Voice is not silenced when sabotaging comms, even when the feature is enabled

### ISSUE THREAD

**Issue by AmitloafTotes** [OhMyGuus/BetterCrewLink#58]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
Even when the feature of sabotaging communicatiosn disables voice is checked, sabotaging communications doesn't disable voice.

**To Reproduce**
Steps to reproduce the behaviour:
1. Check the sabotage communications feature.
2. Play a game
3.  Have the impostor sabotage comms.
4. See that voice is still heard.

**Expected behaviour**
Voice should be silenced

**Desktop (please complete the following information):**
- Windows 10
- Latest versions

**Additional context**
It did work for us before the latest updates

**Comment by OhMyGuus** [comment]
Fixed in commit #1e2587fc2dcfb380e6680b1b4fd0dcd023ac035a  will be released soon, want to make some extra changes and then I will release it :)

**Comment by MatadorProBr** [comment]
The new version of [BetterCrewLink](https://github.com/OhMyGuus/BetterCrewLink/releases/latest) was released so I think I should close this issue
