### ISSUE TITLE
Host not being detected

### ISSUE THREAD

**Issue by BlaCoiso** [OhMyGuus/BetterCrewLink#6]
**Describe the bug** 
Lobby host is not being detected or `gameState.isHost` is not being set

**To Reproduce**
Steps to reproduce the behaviour:
Create a lobby (version 2020.12.5s)
Try to change lobby settings

**Expected behaviour**
Lobby settings can be changed

**Screenshots**

![image](https://user-images.githubusercontent.com/13855359/103043177-e75b2d80-4573-11eb-8871-6acfbdb582c8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro build 19042.685
 - Version: Among Us version 2020.12.5s, CrewLink v1.1.98-beta.5 (latest github release)

**Comment by OhMyGuus** [comment]
Thanks for the find, just saw that I forgot to add the updater for the CLientId,HostId will be fixed in the next update.

**Comment by OhMyGuus** [comment]
Fixed!
