### ISSUE TITLE
Potential incompatability with ExtraRoles mod

### ISSUE THREAD

**Issue by JKohlman** [OhMyGuus/BetterCrewLink#62]
[Extra Roles](https://github.com/NotHunter101/ExtraRolesAmongUs) has been shown to potentially cause issues with memory locations that BetterCrewLink looks for. I'm not sure if this is really feasible to fix but I'm noting it here so it's known.

**Comment by OhMyGuus** [comment]
Need someone with the actual issue to fix it, since I tested it with extra roles and it seemed to work for me.

**Comment by MatadorProBr** [comment]
and also this problem is not only with [Extra Roles](https://github.com/NotHunter101/ExtraRolesAmongUs) but with other mods, such as [Town of Us](https://github.com/slushiegoose/Town-Of-Us)

**Comment by Jasbris** [comment]
> and also this problem is not only with [Extra Roles](https://github.com/NotHunter101/ExtraRolesAmongUs) but with other mods, such as [Town of Us](https://github.com/slushiegoose/Town-Of-Us)

Do you have to mod your root game folder (Steam/steamapps/common/Among Us), or will BetterCrewLink pick up a custom mod folder like "Steam/steamapps/common/Among Us - Town of Impostors"?

**Comment by MatadorProBr** [comment]
> > and also this problem is not only with [Extra Roles](https://github.com/NotHunter101/ExtraRolesAmongUs) but with other mods, such as [Town of Us](https://github.com/slushiegoose/Town-Of-Us)
> 
> Do you have to mod your root game folder (Steam/steamapps/common/Among Us), or will BetterCrewLink pick up a custom mod folder like "Steam/steamapps/common/Among Us - Town of Impostors"?

It takes any mod you are using, as it does not look for the game folder, but rather it looks for whether the game is running through your RAM memory, because whenever you open a game it uses RAM memory

**Comment by OhMyGuus** [comment]
Better-Crewlink looks for the process called "Among Us.exe" in the process list, then it will make an handle and read memory from it. So the folder doesn't matter as long as you don't rename the actual exe. 

However sometimes it bugs out, this because the mod changed some things after Crewlink started, so the best thing to get the mod working for BetterCrewlink is starting the modded game first and then Crewlink. If you do it like that it shouldn't cause an issue.

**Comment by MatadorProBr** [comment]
I will close this issue as it seems that the problem has been solved since I don't see anyone else reporting this bug
