### ISSUE TITLE
Can't hear other players even though on same server

### ISSUE THREAD

**Issue by CaptainKhaid** [OhMyGuus/BetterCrewLink#64]
I have got a problem with BetterCrewLink. 
Somehow in some games, i cannot hear other players, even though i heard them last round. STRG + R also does not fix this problem. NAT Fix also doesn't help. The icon has no Red Mark and we checked all settings to be the same ( Voice Server etc). 
Sadly, i got no real way to reproduce this bug, it just happens randomly. 

Reinstalling Among us and Mods didn't help.
Sometimes it even happens between voting rounds. I hear them one voting round, next round they are silent for me. 

I am playing with "The Other Roles" mod by Eisbison v1.5 and on Windows 10 PC, Game Version 2021.3.5

**Comment by OhMyGuus** [comment]
Yeah this is a weird issue with the mod and bettercrewlink. Saw someone having the same issue yesterday. It's quite hard to diagnose this tho since it doesn't happen all the time.

**Comment by Slipperysnake3** [comment]
Im having the same issue and cant play proximty at all

**Comment by OhMyGuus** [comment]
For these issues you need to join the discord and make a ticket or message me. 

The link is in the readme

**Comment by Slipperysnake3** [comment]
I think I will wait to the next update becuse the issue only appears on
v2.4.0

**Comment by Slipperysnake3** [comment]
Hi betercrewlink still not working for me other playrs can hear but i cant
hesr them
