### ISSUE TITLE
[FEATURE] Repl.it support for server

### ISSUE THREAD

**Issue by Kore-Development** [OhMyGuus/BetterCrewLink#65]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
2. [x] I have checked that someone else has not suggested this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)
3. [x] My feature request is not one of the **commonly suggested features**:
- Linux/MacOS support (is already being development and you can follow this development [clicking here](https://github.com/OhMyGuus/BetterCrewLink/pull/29))
- iOS app (its already being development)

**Is your feature request related to a problem? Please describe.**
Yes. In my opinion, Heroku has too many paid only features such as monthly limits while Repl.it seems to be a lot like Glitch before Glitch added the paid plan.

**Describe the solution you'd like**
I would like support for Repl.it for the server. In my opinion, it's a better alternative to Heroku. As far as I know, Repl.it doesn't have any monthly limits. It does sleep though so if you would like it to be always online you could use a service like UptimeRobot. Repl.it also has HTTPS already, so you don't need to configure HTTPS manually and custom domains are also free.

**Describe alternatives you've considered**
Glitch would have been a very good option before they added the paid version and monthly limits.

**Additional context**

**Comment by OhMyGuus** [comment]
Oh just saw you can't make issues on the server repo, nice request never heard of repl.it but seems like a nice service.
Added the badge to the repo, feel free to make an PR for instructions in the readme about how to run it using repl.it

**Comment by MatadorProBr** [comment]
Added in https://github.com/OhMyGuus/BetterCrewLink-server
