### ISSUE TITLE
[BUG REPORT] Echo Cancellation and Noise Suspension are not working on BetterCrewLink

### ISSUE THREAD

**Issue by MatadorProBr** [OhMyGuus/BetterCrewLink#66]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
2. [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
3. [X] I have checked everyone in my lobby is on the same CrewLink server
4. [X] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
5. [X] I have checked that the CrewLink server I'm using is up to date
6. [ ] I have a screenshot of any errors
7. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

**Describe the bug**
When you activate echo cancellation and noise suspension, nothing seems to happen, echo and noise continue even with both options enabled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'BetterCrewLink Settings'
2. Activate on 'Echo Cancellation and Noise Suspension'
3. See error

**Expected behaviour**
It was for the echo and the noises stopped happening.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 2.4.0]

**Additional context**
N/A

**Comment by OhMyGuus** [comment]
Not gonna improve it until we switch from webrtc to another protocol.

**Comment by MatadorProBr** [comment]
Solution for now:

Use [Krisp](https://krisp.ai/) (program that removes the echo & noise from your microphone) so you practically have a better Echo Cancellation & Noise Suspension than BetterCrewLink (Discord himself uses Krisp to remove Echo & Noise)

Available for: Windows and Mac (sorry Linux users but for now this program does not support Linux)

**Comment by MimzyFang** [comment]
there are alternatives like 
[NoiseTorch](https://github.com/lawl/NoiseTorch) and [Cadmus](https://github.com/josh-richardson/cadmus) for Linux
