### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by flubbe23** [OhMyGuus/BetterCrewLink#69]
I hear everybody in a slower talking robot voice, gettin worse and worse by the second. Nobody else in my friends group has that problem :( Any suggestion?

**Comment by MatadorProBr** [comment]
Did you try to disable VAD?

**Comment by flubbe23** [comment]
Thank you! I opened a ticket in discord, maybe someone can help me :)

**Comment by flubbe23** [comment]
Hi, just wanted you to know, it was my usb headset, that f****d it all up. Thank you guys for everything and the cool mod :)
