### ISSUE TITLE
Discord Server BetterCrewLink 

### ISSUE THREAD

**Issue by BrianPurgert** [OhMyGuus/BetterCrewLink#7]
is there a discord server for people using BetterCrewLink?

**Comment by OhMyGuus** [comment]
There is no at the moment, but I can setup a discord server for support/lobbies if people desire. 
Just to note bettercrewlink works with any voice server (except the lobby settings) so if you are in need of proximity lobbies there are many bigger servers for that.

**Comment by OhMyGuus** [comment]
https://discord.gg/qDqTzvj4SH 
Still making all the channels and stuff but fine.
