### ISSUE TITLE
[FEATURE] Linux support

### ISSUE THREAD

**Issue by OhMyGuus** [OhMyGuus/BetterCrewLink#70]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want that BetterCrewlink fully works on Linux & Windows in the same repo. 

**Additional context**
-- Testing and getting the fork https://github.com/OhMyGuus/BetterCrewlink-Linux merged into the main repo. 

(Will edit this later, this issue is for discussion mostly)

**Comment by Fauli1221** [comment]
Your awesome.
thank you

**Comment by OhMyGuus** [comment]
Linux support is now in this repo and working, if there are any issues with it u can make an issue on this repo now. 

https://github.com/OhMyGuus/BetterCrewLink/wiki/installation#linux
