### ISSUE TITLE
[BUG REPORT] color not match (2.4.4)

### ISSUE THREAD

**Issue by Hoax017** [OhMyGuus/BetterCrewLink#77]
The color in 2.4.4 isn't corresponding

![image](https://user-images.githubusercontent.com/8215575/113338681-b71ceb00-9329-11eb-88d2-42417f3b0b3d.png)

**Comment by Hoax017** [comment]
everyone is red :
![image](https://user-images.githubusercontent.com/8215575/113339543-e718be00-932a-11eb-8054-adb2b917aa96.png)

**Comment by OhMyGuus** [comment]
Forgot to make a bug report of this, thanks. 
This is a known bug, restarting your BetterCrewlink will fix this, will be fixed in next update

**Comment by Hoax017** [comment]
Thanks for your reactivity :)

**Comment by MatadorProBr** [comment]
What, why the Lobby code is "LOBBY"?

**Comment by OhMyGuus** [comment]
Fixed now in latest release
