### ISSUE TITLE
[BUG REPORT] Garbled voice due to exterme resource usage

### ISSUE THREAD

**Issue by w0uld** [OhMyGuus/BetterCrewLink#8]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [X] I am using the Steam version of Among Us
3. [X] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [X] I have checked everyone in my lobby is on the same CrewLink server
5. [X] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [X] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
The application uses a huge amount of system resources -- 4 members of our 10 party playgroup reported 80-100% CPU utilization on their laptops according to task manager, resulting in garbled voice on their end. Other members also saw a surprisingly high CPU utilization, but they have better computers, therefore don't experience any other issues. 
CPU utilization is the highest during gameplay with 10 people.

Note: we checked CrewLink as well -- CrewLink also has a surprisingly high CPU usage, but not as high as BetterCrewLink; this leads me to assume that the problems might be stemming from CrewLink itself, but further enhanced by BetterCrewLink. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Join a proximity game with 10 people.
2. Start playing.
3. Check task manager in the meantime.
4. You should be seeing surprisingly high CPU utilization. 

**Expected behaviour**
Less taxing on system resources.

**Desktop (please complete the following information):**
OS: Windows 10
Version: BetterCrewLink 1.2.14

**Comment by OhMyGuus** [comment]
Will look into it thanks for the report!

**Comment by vrnagy** [comment]
The main source of the usage is the too frequent memory read in https://github.com/OhMyGuus/BetterCrewLink/blob/nightly/src/main/hook.ts#L71 .

It's neccessary for high player speed, but if You only play on regular speeds, then 250ms read is more than adequate.
We use it with that parameter and it uses way less CPU than the original version

**Comment by w0uld** [comment]
> 
> 
> The main source of the usage is the too frequent memory read in https://github.com/OhMyGuus/BetterCrewLink/blob/nightly/src/main/hook.ts#L71 .
> 
> It's neccessary for high player speed, but if You only play on regular speeds, then 250ms read is more than adequate.
> We use it with that parameter and it uses way less CPU than the original version

Szia Robi,
Thanks for the reply. I don't see an option to change the polling rate in the readily available releases -- is it just me, or it's not implemented yet?

**Comment by vrnagy** [comment]
Currently it's only changeable at compilation time, so You have to build Your own release from the source to do it

**Comment by w0uld** [comment]
I see. Thanks for the info 👍

**Comment by vrnagy** [comment]
I have everything installed on my PC so if You want I can build a version for You which have the polling changed to 250ms, so You can test it with Your friends

**Comment by w0uld** [comment]
I'd be happy to test it.

**Comment by vrnagy** [comment]
@w0uld You can download itt from here: https://vrnagy.eu/stuff/Better-CrewLink-Setup-1.2.16.exe Only the polling has been changed

**Comment by sniffingtoad** [comment]
> @w0uld You can download it from here: https://vrnagy.eu/stuff/Better-CrewLink-Setup-1.2.16.exe Only the polling has been changed

I tested it, it doesn't seem to fix it really

**Comment by w0uld** [comment]
Thanks for all the help. CPU utilization remains fairly high, so even if it improved somewhat, unfortunately this doesn't seem to be an ideal solution.

**Comment by OhMyGuus** [comment]
I found the issue with bettercrewlink using too much cpu, there was an issue with the playercount which added alot more cpu. 
Thanks for bringing this to my attention and this will be fixed in the next update (in 30 minutes or so)

**Comment by w0uld** [comment]
Report: The new builds significantly reduce CPU usage when VAD is disabled. Thank you very much for the work put into this, BetterCrewLink is now very usable on weaker hardware as well.
